// Objective-C API for talking to github.com/jondot/primer-bind/primer Go package.
//   gobind -lang=objc -prefix=Go github.com/jondot/primer-bind/primer
//
// File is generated by gobind. Do not edit.

#ifndef __GoPrimer_H__
#define __GoPrimer_H__

#include <Foundation/Foundation.h>
#include "GoUniverse.h"

@class GoPrimerJsonDummy;
@protocol GoPrimerOnIterationDone;
@class GoPrimerOnIterationDone;

@interface GoPrimerJsonDummy : NSObject {
}
@property(strong, readonly) id _ref;

- (id)initWithRef:(id)ref;
@end

@protocol GoPrimerOnIterationDone
- (void)do:(long)p0;
@end

FOUNDATION_EXPORT void GoPrimerBench();

FOUNDATION_EXPORT NSString* GoPrimerProcess(NSString* name, long iters, long size, long workers, long mode, id<GoPrimerOnIterationDone> iterdone);

@class GoPrimerOnIterationDone;

@interface GoPrimerOnIterationDone : NSObject <GoPrimerOnIterationDone> {
}
@property(strong, readonly) id _ref;

- (id)initWithRef:(id)ref;
- (void)do:(long)p0;
@end

#endif
