
// Objective-C API for talking to the following Go packages
//
//	github.com/jondot/primer-bind/primer
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Primer_H__
#define __Primer_H__

#include "GoPrimer.h"
#include "GoUniverse.h"

#endif
